flags: {}
packages:
  - '.'
extra-deps:
  - sqlite-simple-0.4.18.2
  - direct-sqlite-2.3.28
  - simple-sql-parser-0.6.0
  - table-layout-0.9.1.0
  - data-default-instances-base-0.1.0.1
allow-newer: true
resolver: lts-21.17
