flags: {}
packages:
  - '.'
extra-deps:
  - sqlite-simple-0.4.18.0
  - direct-sqlite-2.3.26
  - simple-sql-parser-0.6.0
  - table-layout-0.9.1.0
  - data-default-instances-base-0.1.0.1
resolver: lts-18.28
